# Generated by `mix compux.checksum`. sha256 of each release artifact; every
# download is verified against this map (rustler_precompiled-style).
%{
  "linux-x86_64" => "43a0e3d97566c3c1e13530141f15776b89fb5c5376da9630eb95281c2e1ca148",
  "macos-aarch64" => "f16b5e4775cf57e9035e66947260e7e8116e95e310de2bdb783cefa26d4100e0"
}
