# Generated by `mix compux.checksum`. sha256 of each release artifact; every
# download is verified against this map (rustler_precompiled-style).
%{
  "linux-x86_64" => "feed28540f5b7819bdba0e844a5d32e169143fbfaaf9afde4ddbc44063ed18a0",
  "macos-aarch64" => "1579af722d28449a1d684fc537c7e413fd7234c3904d1d34db30ce5746516ad3"
}
