# Generated by `mix compux.checksum`. sha256 of each release artifact; every
# download is verified against this map (rustler_precompiled-style).
%{
  "linux-x86_64" => "9131bd38c8b53b8976d0aed4ea2315f694ad6097851893ce06d51e01ee5f8610",
  "macos-aarch64" => "30723ab8221cae97d033b1d1e487572c0fac0735fb656d14bfc56829aab1e1d0"
}
