defmodule Mix.Tasks.Compux.Checksum do
  @shortdoc "Generate checksum-compux.exs from local release tarballs"

  @moduledoc """
  Computes the sha256 of each `compux-<version>-<target>.tar.gz` in a directory and
  writes `checksum-compux.exs` (the map `Compux.Binary` verifies downloads against).

  Run it after downloading the GitHub Release tarballs, before `mix hex.publish`,
  and commit the result:

      mix compux.checksum --dir ./dist

  Options:
    * `--dir` — directory holding the tarballs (default `.`)
    * `--out` — output file (default `checksum-compux.exs`)
  """

  use Mix.Task

  @targets ["macos-aarch64", "linux-x86_64"]

  @impl Mix.Task
  def run(argv) do
    {opts, _rest, _invalid} = OptionParser.parse(argv, strict: [dir: :string, out: :string])
    dir = Keyword.get(opts, :dir, ".")
    out = Keyword.get(opts, :out, "checksum-compux.exs")
    version = to_string(Application.spec(:compux, :vsn) || Mix.Project.config()[:version])

    checksums = compute(dir, version)

    if checksums == %{} do
      Mix.raise("no compux-#{version}-<target>.tar.gz found in #{dir}")
    end

    File.write!(out, render(checksums))
    Mix.shell().info("wrote #{map_size(checksums)} checksum(s) for v#{version} to #{out}")
  end

  @doc "sha256 of every present target tarball in `dir` for `version`."
  @spec compute(String.t(), String.t()) :: %{String.t() => String.t()}
  def compute(dir, version) do
    @targets
    |> Enum.map(fn target -> {target, read_sha(Path.join(dir, tarball(version, target)))} end)
    |> Enum.reject(fn {_target, sha} -> is_nil(sha) end)
    |> Map.new()
  end

  defp tarball(version, target), do: "compux-#{version}-#{target}.tar.gz"

  defp read_sha(path) do
    case File.read(path) do
      {:ok, bytes} -> :sha256 |> :crypto.hash(bytes) |> Base.encode16(case: :lower)
      {:error, _reason} -> nil
    end
  end

  defp render(checksums) do
    body =
      checksums
      |> Enum.sort()
      |> Enum.map_join(",\n", fn {target, sha} -> ~s(  "#{target}" => "#{sha}") end)

    """
    # Generated by `mix compux.checksum`. sha256 of each release tarball; every
    # download is verified against this map (rustler_precompiled-style).
    %{
    #{body}
    }
    """
  end
end
